# NumPy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)  #cast this list into an array
                    # you get one dimentional array

In [7]:
arr

array([1, 2, 3])

# To get a two dimentional array:

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,11,2)         # built in range function for numpy
                          # similar to range function

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros(3)       #specific type of arrays in numpy

array([0., 0., 0.])

In [18]:
np.zeros((5,5))         # passing a tuple of the dimension 5x5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# another built in function known as: linspace
np.linspace(0,5,10)

# you get 10 evenly spaced points between 0 and 5 in one dimensioal vector

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [26]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [33]:
np.eye(4)       # an idenity matrix
                # is a useful matrix when dealing with linear algebra problems

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.random.rand(5)

array([0.3938097 , 0.99671854, 0.12083477, 0.01509398, 0.09923535])

In [35]:
np.random.rand(5,5)

array([[0.74254825, 0.72455758, 0.16981619, 0.69593354, 0.24708107],
       [0.69998928, 0.70356652, 0.32530675, 0.06799725, 0.2681813 ],
       [0.34416489, 0.24905703, 0.57857445, 0.87382392, 0.84872203],
       [0.3834736 , 0.70545149, 0.71311735, 0.66019198, 0.35637807],
       [0.43760993, 0.35917875, 0.84806539, 0.72508304, 0.20169381]])

In [36]:
np.random.randn(2)

array([ 1.30441253, -2.22731175])

In [38]:
np.random.randn(4,4)

array([[-1.56971707,  0.49972704,  2.0308508 , -0.86935438],
       [-1.02520011, -1.23008767,  1.22613728, -1.21929252],
       [ 0.71869726,  0.28867505,  0.84947425, -1.14879954],
       [ 0.03411482, -0.66961768,  0.97737914,  0.83222778]])

In [39]:
np.random.randint(1,100)         # you get a random integer from 
                                 # 1 to 100

75

In [40]:
np.random.randint(1,100,10)   # 10 random ineteger

array([39, 26, 21, 60, 47, 96, 52, 21, 66, 77])

In [42]:
arr = np.arange(25)

In [43]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [45]:
ranarr = np.random.randint(0,50,10)

In [46]:
ranarr

array([25, 49, 34,  1, 34, 25, 21, 35, 21,  0])

In [50]:
arr.reshape(5,5)         # need to be the samze size of the number of elements you have

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
ranarr

array([25, 49, 34,  1, 34, 25, 21, 35, 21,  0])

In [52]:
ranarr.max()

49

In [53]:
ranarr.min()

0

In [54]:
ranarr

array([25, 49, 34,  1, 34, 25, 21, 35, 21,  0])

In [55]:
ranarr.argmax()

1

In [59]:
ranarr.argmin()

9

In [60]:
# more useful methods:
arr.shape

(25,)

In [62]:
arr = arr.reshape(5,5)

In [63]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
arr.dtype

dtype('int32')

In [2]:
from numpy.random import randint

In [4]:
randint(2,10)

8