# NumPy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]       # indexing start at 0

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]   # start at 0 and end at 4

array([ 5,  6,  7,  8,  9, 10])

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
arr = np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [19]:
slice_of_arr[:] = 99 

In [20]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [21]:
arr   # the original array changes as well

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:] = 100

In [27]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
 # Note that when you make a copy, the original array doesn't change
 # the .copy() is very important   

# We will create a 2D array

In [4]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,40,45]])

In [5]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [6]:
arr_2d[0][0]   # grabbing the vale in first row, first column

5

In [7]:
arr_2d[0]

array([ 5, 10, 15])

In [8]:
arr_2d[1][1]

25

In [9]:
arr_2d[2][1]  # the first bracket is row
              # the s

40

In [10]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [11]:
arr_2d[1,2]

30

In [13]:
# same thing as:
arr_2d[1][2]   # first is row
               # second is column

30

In [14]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [15]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [17]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [18]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Grab subsections using slice notations

# Conditional selection

In [4]:
arr2 = np.arange(1,11)

In [5]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
bool_arr = arr2 > 5

In [10]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [11]:
arr2[bool_arr]

array([ 6,  7,  8,  9, 10])

In [13]:
arr2[arr2>5]

array([ 6,  7,  8,  9, 10])

In [14]:
arr2[arr2 < 3]

array([1, 2])

In [16]:
arr_2d = np.arange(50).reshape(5,10)

In [17]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [18]:
# practice how to grab chunks and use bracket notations

In [20]:
arr_2d[1:3]  # grabbing from 13 and 14

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [21]:
arr_2d[1:3,3:5]  

array([[13, 14],
       [23, 24]])

Remember, first bracket is rows
second bracket is columns

In [23]:
# try grabbing 16 and 17
arr_2d[1:3, 6:8]

array([[16, 17],
       [26, 27]])

In [26]:
# try grabbing 34
arr_2d[3,4]

34

In [27]:
# try grabbing 34 and 35
arr_2d[3, 4:6]

array([34, 35])

In [28]:
arr_2d[3:5, 4:6]

array([[34, 35],
       [44, 45]])